---
apiVersion: v1
kind: Namespace
metadata:
  name: minions
  labels:
    app: minio

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minions
  labels:
    app: minio
type: Opaque
data:
  MINIO_ROOT_PASSWORD: YWRtaW5hZG1pbg==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minions
data:
  MINIO_ROOT_USER: admin