---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codeapp-cm
  namespace: codens
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-167.172.7.185.nip.io

--- 
apiVersion: v1
kind: Secret
metadata:
  name: codeapp-secret
  namespace: codens
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=
